spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myemployees
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 80

mybatis:
  mapper-locations: classpath:com/example/modelmybatis/mapper/*.xml
  type-aliases-package: com.example.modelmybatis.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl